export const FETCH_COUNTRIES = "FETCH_COUNTRIES";

export const NEW_COUNTRIES = "NEW_COUNTRIES";

export const COUNTRY_CHANGED = "COUNTRY_CHANGED";

export const STATE_CHANGED = "STATE_CHANGED";

export const POPULATE_STATES = "POPULATE_STATES";

export const GET_PAGE_DATA = "GET_PAGE_DATA";
